import { DataPattern } from "./types";

const projectsData: DataPattern[] = [
  {
    title: "Omnifood",
    tools: "Vanilla JS",
    // img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/omnifood.png",
    link: "https://omnifood-by-peach.netlify.app/",
    year: "2022",
    type: "learning project",
  },
  {
    title: "Natours",
    tools: "SCSS",
    // img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/natours.png",
    link: "https://natours-by-peach.netlify.app/",
    year: "2022",
    type: "learning project",
  },
  {
    title: "Trillo",
    tools: "SCSS",
    // img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/trillo.png",
    link: "https://trillo-by-peach.netlify.app/",
    year: "2022",
    type: "learning project",
  },
  {
    title: "Nexter",
    tools: "SCSS",
    // img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/nexter.png",
    link: "https://nexter-by-peach.netlify.app/",
    year: "2022",
    type: "learning project",
  },
  {
    title: "Guess My Number",
    tools: "Vanilla JS",
    // img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/guess_my_num.png",
    link: "https://guessmynum-by-peach.netlify.app/",
    year: "2022",
    type: "learning project",
  },
  {
    title: "Bankist App",
    tools: "Vanilla JS",
    // img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/bankist_app.png",
    link: "https://bankistapp-by-peach.netlify.app/",
    year: "2022",
    type: "learning project",
  },
  {
    title: "Pig Game",
    tools: "Vanilla JS",
    // img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/pig_game.png",
    link: "https://piggame-by-peach.netlify.app/",
    year: "2022",
    type: "learning project",
  },
  {
    title: "Bankist Page",
    tools: "Vanilla JS",
    // img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/bankist_page.png",
    link: "https://bankist-by-peach.netlify.app/",
    year: "2022",
    type: "learning project",
  },
  {
    title: "Forkify App",
    tools: "Vanilla JS",
    // img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/forkify.png",
    link: "https://forkify-by-peach.netlify.app/",
    year: "2023",
    type: "learning project",
  },
  {
    title: "E-Learning Landing Page",
    tools: "SCSS",
    // img: "https://raw.githubusercontent.com/Peac-h/6_Skilled-e-Learning-Landing-Page/main/Screenshot.png",
    link: "https://peac-h.github.io/6_Skilled-e-Learning-Landing-Page/",
    year: "2022",
    type: "website clone",
  },
  {
    title: "Art Gallery Website",
    tools: "SCSS",
    // img: "https://raw.githubusercontent.com/Peac-h/7_Art-Gallery-Website/main/Screenshot.png",
    link: "https://peac-h.github.io/7_Art-Gallery-Website/",
    year: "2022",
    type: "website clone",
  },
  {
    title: "Equalizer Landing Page",
    tools: "SCSS",
    // img: "https://raw.githubusercontent.com/Peac-h/8_Equalizer-Landing-Page/main/Screenshot.png",
    link: "https://peac-h.github.io/8_Equalizer-Landing-Page/",
    year: "2022",
    type: "website clone",
  },
  {
    title: "Typemaster Landing Page",
    tools: "SCSS",
    // img: "https://raw.githubusercontent.com/Peac-h/9_Typemaster-Landing-Page/main/Screenshot.png",
    link: "https://peac-h.github.io/9_Typemaster-Landing-Page/",
    year: "2022",
    type: "website clone",
  },
  {
    title: "Single Page Portfolio",
    tools: "SCSS",
    // img: "https://raw.githubusercontent.com/Peac-h/10.0_simple_portfolio_page/main/Desktop.png",
    link: "https://peac-h.github.io/10.0_simple_portfolio_page/",
    year: "2023",
    type: "website clone",
  },
  {
    title: "CSS Hovers",
    tools: "SCSS",
    // img: "https://raw.githubusercontent.com/Peac-h/14_css-hovers/main/Screen%20Shot%20'2023'-03-01%20at%2010.12.45%20PM.png",
    link: "https://peac-h.github.io/14_css-hovers/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "Apple Calculator",
    tools: "Vanilla JS",
    // img: "https://raw.githubusercontent.com/Peac-h/20_javascript_calculator/main/screenshot.png",
    link: "https://peac-h.github.io/20_javascript_calculator/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "Guess The Spell",
    tools: "Vanilla JS",
    // img: "https://raw.githubusercontent.com/Peac-h/21_guess_the_spell/main/Screen%20Shot%20'2023'-03-27%20at%2010.35.12%20PM.png",
    link: "https://peac-h.github.io/21_guess_the_spell/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "Speed Typing Game",
    tools: "Vanilla JS",
    // img: "https://raw.githubusercontent.com/Peac-h/22_speed_typing_game/main/Screenshot2.png",
    link: "https://peac-h.github.io/22_speed_typing_game/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "Weather App",
    tools: "Vanilla JS",
    // img: "https://raw.githubusercontent.com/Peac-h/23_weather_app/main/screenDesktop.png",
    link: "https://p-weather-app.netlify.app/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "Search The World",
    tools: "Vanilla JS",
    // img: "https://raw.githubusercontent.com/Peac-h/24_search_the_world/main/Screen%20Shot%20'2023'-04-08%20at%207.51.10%20PM.png",
    link: "https://peac-h.github.io/24_search_the_world/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "ToDo App",
    tools: "Vanilla JS",
    // img: "https://raw.githubusercontent.com/Peac-h/25_todo_app/main/Screenshot.png",
    link: "https://peac-h.github.io/25_todo_app/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "Music App",
    tools: "Vanilla JS",
    // img: "https://raw.githubusercontent.com/Peac-h/26_music-player/main/Screen%20Shot%20'2023'-04-21%20at%209.17.58%20PM.png",
    link: "https://peac-h.github.io/26_music-player/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "A Traveller's Notebook",
    tools: "Vanilla JS",
    // img: "https://raw.githubusercontent.com/Peac-h/27_leaflet_project/main/Screen%20Shot%20'2023'-05-07%20at%2012.08.40%20PM.png",
    link: "https://peac-h.github.io/27_leaflet_project/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "Tic Tac Toe",
    tools: "jQuery",
    // img: "https://raw.githubusercontent.com/Peac-h/28_tic-tac-toe/main/Screen%20Shot%20'2023'-05-07%20at%201.17.21%20PM.png",
    link: "https://peac-h.github.io/28_tic-tac-toe/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "Introducing ChatGPT",
    tools: "TS",
    status: "Working on currently",
    year: "2023",
    type: "website clone",
  },
  {
    title: "Peach Folio '90s",
    tools: "Vanilla JS",
    // img: ,
    link: "https://peachfolio90s.com/",
    year: "2023",
    type: "personal project",
  },
];

export default projectsData;
