import { DataPattern } from "./types";

const projectsData: DataPattern[] = [
  {
    title: "Omnifood",
    tools: "Vanilla JS",
    link: "https://omnifood-by-peach.netlify.app/",
    year: "2022",
    type: "learning project",
  },
  {
    title: "Natours",
    tools: "SCSS",
    link: "https://natours-by-peach.netlify.app/",
    year: "2022",
    type: "learning project",
  },
  {
    title: "Trillo",
    tools: "SCSS",
    link: "https://trillo-by-peach.netlify.app/",
    year: "2022",
    type: "learning project",
  },
  {
    title: "Nexter",
    tools: "SCSS",
    link: "https://nexter-by-peach.netlify.app/",
    year: "2022",
    type: "learning project",
  },
  {
    title: "Guess My Number",
    tools: "Vanilla JS",
    link: "https://guessmynum-by-peach.netlify.app/",
    year: "2022",
    type: "learning project",
  },
  {
    title: "Bankist App",
    tools: "Vanilla JS",
    link: "https://bankistapp-by-peach.netlify.app/",
    year: "2022",
    type: "learning project",
  },
  {
    title: "Pig Game",
    tools: "Vanilla JS",
    link: "https://piggame-by-peach.netlify.app/",
    year: "2022",
    type: "learning project",
  },
  {
    title: "Bankist Page",
    tools: "Vanilla JS",
    link: "https://bankist-by-peach.netlify.app/",
    year: "2022",
    type: "learning project",
  },
  {
    title: "Forkify App",
    tools: "Vanilla JS",
    link: "https://forkify-by-peach.netlify.app/",
    year: "2023",
    type: "learning project",
  },
  {
    title: "E-Learning Landing Page",
    tools: "SCSS",
    link: "https://peac-h.github.io/6_Skilled-e-Learning-Landing-Page/",
    year: "2022",
    type: "website clone",
  },
  {
    title: "Art Gallery Website",
    tools: "SCSS",
    link: "https://peac-h.github.io/7_Art-Gallery-Website/",
    year: "2022",
    type: "website clone",
  },
  {
    title: "Equalizer Landing Page",
    tools: "SCSS",
    link: "https://peac-h.github.io/8_Equalizer-Landing-Page/",
    year: "2022",
    type: "website clone",
  },
  {
    title: "Typemaster Landing Page",
    tools: "SCSS",
    link: "https://peac-h.github.io/9_Typemaster-Landing-Page/",
    year: "2022",
    type: "website clone",
  },
  {
    title: "Single Page Portfolio",
    tools: "SCSS",
    link: "https://peac-h.github.io/10.0_simple_portfolio_page/",
    year: "2023",
    type: "website clone",
  },
  {
    title: "CSS Hovers",
    tools: "SCSS",
    link: "https://peac-h.github.io/14_css-hovers/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "Apple Calculator",
    tools: "Vanilla JS",
    link: "https://peac-h.github.io/20_javascript_calculator/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "Guess The Spell",
    tools: "Vanilla JS",
    link: "https://peac-h.github.io/21_guess_the_spell/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "Speed Typing Game",
    tools: "Vanilla JS",
    link: "https://peac-h.github.io/22_speed_typing_game/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "Weather App",
    tools: "Vanilla JS",
    link: "https://p-weather-app.netlify.app/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "Search The World",
    tools: "Vanilla JS",
    link: "https://peac-h.github.io/24_search_the_world/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "ToDo App",
    tools: "Vanilla JS",
    link: "https://peac-h.github.io/25_todo_app/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "Music App",
    tools: "Vanilla JS",
    link: "https://peac-h.github.io/26_music-player/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "A Traveller's Notebook",
    tools: "Vanilla JS",
    link: "https://peac-h.github.io/27_leaflet_project/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "Tic Tac Toe",
    tools: "jQuery",
    link: "https://peac-h.github.io/28_tic-tac-toe/",
    year: "2023",
    type: "personal project",
  },
  {
    title: "Introducing ChatGPT",
    tools: "TS",
    link: "https://introducing-chatgpt-clone.netlify.app/",
    year: "2023",
    type: "website clone",
  },
  {
    title: "Spotify Landing Page",
    tools: "React",
    status: "Working on currently",
    year: "2024",
    type: "website clone",
  },
  {
    title: "Peach Folio '90s",
    tools: "Vanilla JS",
    link: "https://peachfolio90s.com/",
    year: "2023",
    type: "personal project",
  },
];

export default projectsData;
